- name: Build Infrastructure with terraform
  on:
    pull_request:

  env:
    ARM_CLIENT_ID:
    ARM_CLIENT_SECRET:
    ARM_TENANT_ID:
    ARM_SUBSCRIPTION_ID:

  jobs:
    terraform:
      name: "Terraform Plan"
      run-on: ubuntu-latest
      environment:
        name: dev
      defaults:
        run:
          shell: /bin/bash
          working-directory: ./dev
      permissions:
        contents: read
        pull-requests: write
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Setup terraform
          uses:  hashicorp/setup-terraform@v2
          wrapper: false

        - name: Terraform init
          id: init
          run: terraform init

        - name: Terraform apply
          id: plan
          run: terraform plan -no-color
          
